# Generated by Django 5.2.4 on 2025-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('ord_no', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('state', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
