# Generated by Django 5.2.4 on 2025-09-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m_shoes', '0002_alter_orders_ord_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='utr',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
