# Generated by Django 5.2.4 on 2025-08-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imageset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Material', models.CharField(max_length=30, null=True)),
                ('Heel_type', models.CharField(max_length=30, null=True)),
                ('Water_resistance_level', models.CharField(max_length=30, null=True)),
                ('Sole_material', models.CharField(max_length=30, null=True)),
                ('Style', models.CharField(max_length=30, null=True)),
                ('Country_of_Origin', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size1', models.CharField(max_length=10, null=True)),
                ('size2', models.CharField(max_length=10, null=True)),
                ('size3', models.CharField(max_length=10, null=True)),
                ('size4', models.CharField(max_length=10, null=True)),
                ('size5', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prce', models.CharField(max_length=10)),
                ('offer', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=30, null=True)),
                ('inf1', models.CharField(max_length=50, null=True)),
                ('inf2', models.CharField(max_length=50, null=True)),
                ('inf3', models.CharField(max_length=50, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.brand')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.cate')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.gender')),
                ('image_set', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.imageset')),
                ('material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.material')),
                ('size', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.size')),
            ],
        ),
    ]
