# Generated by Django 5.2.4 on 2025-08-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cart_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('user_name', models.CharField(max_length=20)),
                ('user_com', models.CharField(max_length=200)),
            ],
        ),
    ]
