# Generated by Django 5.2.4 on 2025-08-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
